name: Deploy to Production

on:
  push:
    branches:
      - development  # Triggers when you push to development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          # This handles the +ssh-rsa requirement if your server is older
          key_algorithms: +ssh-rsa 
          script: |
            cd portal.employme.ng/Files
            git pull origin development